//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubidium
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftMetric : IEntity
    {
        public int Id { get; set; }
        public int aircraft_id { get; set; }
        public System.DateTime date { get; set; }
        public decimal fuel_consumption { get; set; }
        public int passenger_load { get; set; }
        public decimal cargo_load { get; set; }
        public decimal water_level { get; set; }
        public decimal oil_level { get; set; }
        public decimal technical_condition { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
    }
}
