//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubidium
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aircraft()
        {
            this.AircraftMetrics = new HashSet<AircraftMetric>();
        }
    
        public int Id { get; set; }
        public string registration_number { get; set; }
        public string model { get; set; }
        public int year_of_manufacture { get; set; }
        public int passenger_capacity { get; set; }
        public decimal cargo_capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AircraftMetric> AircraftMetrics { get; set; }
    }
}
