//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubidium
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baggage : IEntity
    {
        public int Id { get; set; }
        public int passenger_number { get; set; }
        public string passenger_name { get; set; }
        public string passenger_sername { get; set; }
        public int flight_id { get; set; }
        public decimal weight { get; set; }
        public string status { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
