//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubidium
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baggage : IEntity
    {
        public int Id { get; set; }
        public int passenger_number { get; set; }
        public string passenger_name { get; set; }
        public string passenger_sername { get; set; }
        public int flight_id { get; set; }
        public decimal weight { get; set; }
        public string status { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
