//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateAssignments
    {
        public int AssignmentID { get; set; }
        public int FlightID { get; set; }
        public string GateNumber { get; set; }
        public Nullable<System.DateTime> AssignedTime { get; set; }
    
        public virtual Flights Flights { get; set; }
    }
}
