//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportStaffDBEntities : DbContext
    {
        public static AirportStaffDBEntities _context;
        public AirportStaffDBEntities()
            : base("name=AirportStaffDBEntities")
        {
        }

        public static AirportStaffDBEntities GetContext()
        {
            if (_context == null)
                _context = new AirportStaffDBEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Baggage> Baggage { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FlightCrew> FlightCrew { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<GateAssignments> GateAssignments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
